stages:
  - test
  - build


run_tests:
  stage: test
  image: python:3.6-alpine
  before_script:
    - pip install --no-cache-dir -r requirements.txt -r requirements-test.txt
  script:
    - python -m unittest discover -s tests/

build_coverage_report:
  extends: run_tests
  script:
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: .coverage

build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${YC_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "oauth" "${YC_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${YC_REGISTRY}/${YC_REGISTRY_ID}/${APP_NAME}:${CI_COMMIT_SHORT_SHA}"
