---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: searchEngine
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: searchEngine
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui
      labels:
        app: searchEngine
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: ui
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: ui
              protocol: TCP
          env:
            - name: MONGO_HOST
              value: {{  .Values.postHost | default (printf "%s-mongodb" .Release.Name) }}
            - name: MONGO_PORT
              value: {{  .Values.postPort | default "27017" | quote }}
